-- Migration: Chatbot Configuration Table
-- Description: Creates table to store chatbot configuration for each consultorio
-- Date: 2024-01-15

CREATE TABLE IF NOT EXISTS chatbot_configuracion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    negocio_id INT NOT NULL,
    configuracion JSON NOT NULL COMMENT 'Structured chatbot configuration (business info, services, policies, FAQs)',
    prompt_completo TEXT NOT NULL COMMENT 'Complete prompt generated by frontend, ready for GPT consumption',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    UNIQUE KEY idx_negocio_id (negocio_id),
    FOREIGN KEY (negocio_id) REFERENCES consultorios(id) ON DELETE CASCADE,

    -- Indexes for performance
    INDEX idx_chatbot_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Chatbot configuration storage with hybrid MariaDB+Firestore strategy';
